# # MoveIt uses this configuration for controller management

# moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

# moveit_simple_controller_manager:
#   controller_names:
#     - arm_controller

# arm_controller:
#   type: FollowJointTrajectory
#   joints:
#     - base_first_joint
#     - first_second_joint
#     - second_third_joint

# MoveIt uses this configuration for controller management
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller

  # This MUST be indented under moveit_simple_controller_manager
  arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: True
    joints:
      - base_first_joint
      - first_second_joint
      - second_third_joint
